### PR TITLE
Converted all country names to upper case.

### PR DESCRIPTION
**Pull request by tucotuco**

### CODE REVIEW

**Comment by timrobertson100** [comment]
Hi John

Can you please explain why you are doing this conversion? Would running in case insensitive mode not satisfy the goal?

https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/core/DictionaryBackedParser.java#L29

**Comment by tucotuco** [comment]
For consistency. All but 85 records were not all uppercase, and that could not have been so from the source. For me personally I can deal with it in any way, but was making all upper case in anticipation of providing you with thousands more we have seen in VerNet (10k+ total) that you are sheltered from because we clean up country before it goes on IPT.

**Comment by timrobertson100** [comment]
Thanks.  I don't imagine it will affect anything dramatically as I can't foresee a scenario whereby the user would want it to behave differently for e.g. Britain vs. BRITIAN vs britain.

They were indeed from sources by the way.  Back in 2007 I took verbatim values as I saw them and mapped them manually - and then lost the ability to keep up.  Those keys were in varying case.

**Comment by MattBlissett** [comment]
Thanks @tucotuco, I know this took a long time, but I wanted to format the dictionary consistently with the others so it's easier for us to maintain.

**Comment by tucotuco** [comment]
Welcome!

**Pull request merged**
